<?php

use Illuminate\Database\Seeder;

class StageComponentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stage_components')->delete();
        
        \DB::table('stage_components')->insert(array (
            0 => 
            array (
                'id' => 2,
                'stage_id' => 22,
                'name' => 'Receipt of Original Clearance Documents',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '15',
                'description' => 'Receipt of Clearance documents from the Client',
                'components' => NULL,
                'created_at' => '2018-10-17 08:58:43',
                'updated_at' => '2018-10-17 08:58:43',
            ),
            1 => 
            array (
                'id' => 3,
                'stage_id' => 24,
                'name' => 'Initiating IDF',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '30',
                'description' => 'Initiating IDF',
                'components' => NULL,
                'created_at' => '2018-10-17 08:59:50',
                'updated_at' => '2018-10-17 08:59:50',
            ),
            2 => 
            array (
                'id' => 4,
                'stage_id' => 25,
                'name' => 'Receipt of Original Clearance Documents',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '15',
                'description' => 'Receipt of Clearance documents from the Client',
                'components' => NULL,
                'created_at' => '2018-10-17 09:00:27',
                'updated_at' => '2018-10-17 09:00:27',
            ),
            3 => 
            array (
                'id' => 5,
                'stage_id' => 26,
                'name' => 'Processing of Shipping Line Charges and Manifest',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '60',
                'description' => 'Collecting Shipping Line Invoice and Manifest from Shipping Line',
                'components' => NULL,
                'created_at' => '2018-10-18 16:53:49',
                'updated_at' => '2018-10-18 16:53:49',
            ),
            4 => 
            array (
                'id' => 6,
                'stage_id' => 27,
                'name' => 'Shipping Line Payment Application',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '15',
                'description' => 'Process LPO o send to Client for Payment',
                'components' => NULL,
                'created_at' => '2018-10-18 16:56:05',
                'updated_at' => '2018-10-18 16:56:05',
            ),
            5 => 
            array (
                'id' => 7,
                'stage_id' => 28,
                'name' => 'Delivery Order',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '240',
                'description' => 'Process Delivery order with the Shipping Agent',
                'components' => NULL,
                'created_at' => '2018-10-18 16:57:02',
                'updated_at' => '2018-10-18 16:57:02',
            ),
            6 => 
            array (
                'id' => 8,
                'stage_id' => 29,
                'name' => 'Customs Declaration',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '30',
                'description' => 'Lodging Customs entry Online',
                'components' => NULL,
                'created_at' => '2018-10-18 16:58:19',
                'updated_at' => '2018-10-18 16:58:19',
            ),
            7 => 
            array (
                'id' => 9,
                'stage_id' => 30,
                'name' => 'Tax Payment',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '0',
                'description' => 'Tax Payment by the Importer',
                'components' => '["Client"]',
                'created_at' => '2018-10-18 16:59:39',
                'updated_at' => '2018-10-18 16:59:39',
            ),
            8 => 
            array (
                'id' => 11,
                'stage_id' => 31,
                'name' => 'Processing at DPC',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '1440',
                'description' => 'Processing of Customs entry by Customs at DPC',
                'components' => '["External Process"]',
                'created_at' => '2018-10-18 17:01:05',
                'updated_at' => '2018-10-18 17:01:05',
            ),
            9 => 
            array (
                'id' => 12,
                'stage_id' => 32,
                'name' => 'Physical Verification',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '1440',
                'description' => 'Physical Verification',
                'components' => '["At the Clearance Station"]',
                'created_at' => '2018-10-18 17:02:05',
                'updated_at' => '2018-10-18 17:02:05',
            ),
            10 => 
            array (
                'id' => 13,
                'stage_id' => 33,
                'name' => 'Release',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '0',
                'description' => 'Release with Government Agencies',
                'components' => '["External Process"]',
                'created_at' => '2018-10-18 17:02:57',
                'updated_at' => '2018-10-18 17:02:57',
            ),
            11 => 
            array (
                'id' => 14,
                'stage_id' => 34,
                'name' => 'Processing Terminal Invoice',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '60',
                'description' => 'Terminal invoice by KPA/CFS',
                'components' => '["External Process"]',
                'created_at' => '2018-10-18 17:03:54',
                'updated_at' => '2018-10-18 17:03:54',
            ),
            12 => 
            array (
                'id' => 15,
                'stage_id' => 35,
                'name' => 'Payment of Terminal Invoice',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '120',
                'description' => 'Payment by Finance/Client of Ledger Account',
                'components' => NULL,
                'created_at' => '2018-10-18 17:04:54',
                'updated_at' => '2018-10-18 17:04:54',
            ),
            13 => 
            array (
                'id' => 16,
                'stage_id' => 36,
                'name' => 'Gate Pass and Loading',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '120',
                'description' => 'Processing Gate Pass and Loading',
                'components' => '["External process"]',
                'created_at' => '2018-10-18 17:05:50',
                'updated_at' => '2018-10-18 17:05:50',
            ),
            14 => 
            array (
                'id' => 17,
                'stage_id' => 37,
                'name' => 'Loading',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '300',
                'description' => 'Loading from the Terminal',
                'components' => NULL,
                'created_at' => '2018-10-18 17:06:31',
                'updated_at' => '2018-10-18 17:06:31',
            ),
            15 => 
            array (
                'id' => 18,
                'stage_id' => 38,
                'name' => 'Receipt of Original Clearance Documents',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '15',
                'description' => 'Receipt of Clearance documents from the Client',
                'components' => '["Export"]',
                'created_at' => '2018-10-18 17:07:10',
                'updated_at' => '2018-10-18 17:07:10',
            ),
            16 => 
            array (
                'id' => 19,
                'stage_id' => 39,
                'name' => 'Collection of Empty Containers',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '240',
                'description' => 'Collection of Empty Containers from the Depot',
                'components' => '["Not Applicable for Airfreights and LCLS."]',
                'created_at' => '2018-10-18 17:08:26',
                'updated_at' => '2018-10-18 17:08:26',
            ),
            17 => 
            array (
                'id' => 20,
                'stage_id' => 40,
                'name' => 'Customs Declaration',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '30',
                'description' => 'Lodging Customs entry Online',
                'components' => '["Export"]',
                'created_at' => '2018-10-18 17:09:36',
                'updated_at' => '2018-10-18 17:09:36',
            ),
            18 => 
            array (
                'id' => 21,
                'stage_id' => 41,
                'name' => 'Processing at DPC',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '1440',
                'description' => 'processing at DPC',
                'components' => '["External Process"]',
                'created_at' => '2018-10-18 17:10:15',
                'updated_at' => '2018-10-18 17:10:15',
            ),
            19 => 
            array (
                'id' => 22,
                'stage_id' => 42,
                'name' => 'Stuffing',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '1440',
                'description' => 'Stuffing in the presence of Customs Officials',
                'components' => NULL,
                'created_at' => '2018-10-18 17:11:11',
                'updated_at' => '2018-10-18 17:11:11',
            ),
            20 => 
            array (
                'id' => 23,
                'stage_id' => 43,
                'name' => 'Stuffing Report, and Release',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '60',
                'description' => 'Report by the allocated Customs Officer',
                'components' => '["External Process"]',
                'created_at' => '2018-10-18 17:11:59',
                'updated_at' => '2018-10-18 17:11:59',
            ),
            21 => 
            array (
                'id' => 24,
                'stage_id' => 44,
                'name' => 'Terminal Invoice',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '60',
                'description' => 'Secure Terminal Invoice',
                'components' => NULL,
                'created_at' => '2018-10-18 17:12:36',
                'updated_at' => '2018-10-18 17:12:36',
            ),
            22 => 
            array (
                'id' => 25,
                'stage_id' => 45,
                'name' => 'Gate In the Export Shipment',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '0',
                'description' => 'Gate In the point of Export',
                'components' => NULL,
                'created_at' => '2018-10-18 17:13:08',
                'updated_at' => '2018-10-18 17:13:08',
            ),
            23 => 
            array (
                'id' => 27,
                'stage_id' => 46,
                'name' => 'Scanning/Verification',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '1440',
                'description' => 'Scanning/Verification',
                'components' => '["External Process"]',
                'created_at' => '2018-10-18 17:13:54',
                'updated_at' => '2018-10-18 17:13:54',
            ),
            24 => 
            array (
                'id' => 28,
                'stage_id' => 47,
                'name' => 'Release',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '120',
                'description' => 'Release with all Government Agencies',
                'components' => '["Release by Government Agencies"]',
                'created_at' => '2018-10-18 17:14:58',
                'updated_at' => '2018-10-18 17:14:58',
            ),
            25 => 
            array (
                'id' => 29,
                'stage_id' => 48,
                'name' => 'Handing Over',
                'type' => 'file',
                'required' => 1,
                'notification' => 1,
                'timing' => '60',
                'description' => 'Hand Over to the Terminal Operator',
                'components' => NULL,
                'created_at' => '2018-10-18 17:15:45',
                'updated_at' => '2018-10-18 17:15:45',
            ),
            26 => 
            array (
                'id' => 30,
                'stage_id' => 24,
                'name' => 'Indigo Bond',
                'type' => 'checkbox',
                'required' => 1,
                'notification' => 1,
                'timing' => 'Voluptatem Deserunt',
                'description' => 'Consequatur aut volu',
                'components' => '["Ad sunt laborum impe"]',
                'created_at' => '2019-10-14 11:13:16',
                'updated_at' => '2019-10-14 11:13:16',
            ),
            27 => 
            array (
                'id' => 31,
                'stage_id' => 24,
                'name' => 'Mufutau Richards',
                'type' => 'checkbox',
                'required' => 0,
                'notification' => 0,
                'timing' => 'Aut sit maxime omnis',
                'description' => 'Ad labore velit eu',
                'components' => '["Quia sunt sint volup"]',
                'created_at' => '2019-10-18 11:06:43',
                'updated_at' => '2019-10-18 11:06:43',
            ),
            28 => 
            array (
                'id' => 32,
                'stage_id' => 24,
                'name' => 'Mufutau Richards',
                'type' => 'checkbox',
                'required' => 0,
                'notification' => 0,
                'timing' => 'Aut sit maxime omnis',
                'description' => 'Ad labore velit eu',
                'components' => '["Quia sunt sint volup"]',
                'created_at' => '2019-10-18 11:06:44',
                'updated_at' => '2019-10-18 11:06:44',
            ),
            29 => 
            array (
                'id' => 33,
                'stage_id' => 24,
                'name' => 'Mufutau Richards',
                'type' => 'checkbox',
                'required' => 0,
                'notification' => 0,
                'timing' => 'Aut sit maxime omnis',
                'description' => 'Ad labore velit eu',
                'components' => '["Quia sunt sint volup"]',
                'created_at' => '2019-10-18 11:06:44',
                'updated_at' => '2019-10-18 11:06:44',
            ),
            30 => 
            array (
                'id' => 34,
                'stage_id' => 24,
                'name' => 'Branden Leblanc',
                'type' => 'text',
                'required' => 1,
                'notification' => 1,
                'timing' => 'Sunt officiis id u',
                'description' => 'Id reprehenderit re',
                'components' => '["In nostrud laboriosa"]',
                'created_at' => '2019-10-18 11:09:16',
                'updated_at' => '2019-10-18 11:09:16',
            ),
            31 => 
            array (
                'id' => 35,
                'stage_id' => 31,
                'name' => 'Regional',
                'type' => 'text',
                'required' => 0,
                'notification' => 0,
                'timing' => '99',
                'description' => 'Used at district level',
                'components' => '["jjj"]',
                'created_at' => '2019-10-30 14:35:49',
                'updated_at' => '2019-10-30 14:35:49',
            ),
            32 => 
            array (
                'id' => 36,
                'stage_id' => 24,
                'name' => 'Kiona Ratliff',
                'type' => 'checkbox',
                'required' => 0,
                'notification' => 0,
                'timing' => 'Nulla ad perferendis',
                'description' => 'In incididunt nisi d',
                'components' => '["Possimus ab earum q"]',
                'created_at' => '2019-10-31 20:39:36',
                'updated_at' => '2019-10-31 20:39:36',
            ),
            33 => 
            array (
                'id' => 37,
                'stage_id' => 24,
                'name' => 'Johnson Didinya',
                'type' => 'file',
                'required' => 0,
                'notification' => 0,
                'timing' => 'Rem sed sunt adipis',
                'description' => 'Duis quis quia praes',
                'components' => '["Voluptatibus tempora"]',
                'created_at' => '2019-11-07 05:49:36',
                'updated_at' => '2019-11-07 05:49:36',
            ),
        ));
        
        
    }
}